version: "3"

services:
  app:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    restart: always
    networks:
      - app-network
    ports:
      - '8080:8000'
    volumes:
      - ./:/usr/src/project/
    working_dir: /usr/src/project/
    command: sh -c "python -m src.backend.bot & python -m src.backend.api"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    networks:
      - app-network
    env_file:
      - ./.env
    ports:
      - '5432'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network: