version: "3"

services:

  migrate:
    build: .
    container_name: migrate
    depends_on:
      - database
    networks:
      - app-network
    working_dir: /usr/src/project/
    command: alembic upgrade head

  app:
    build: .
    restart: always
    container_name: app
    networks:
      - app-network
    volumes:
      - ./:/usr/src/project/
    working_dir: /usr/src/project/
    command: python -m app

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    networks:
      - app-network
    env_file:
      - ./.env
    ports:
      - '5432'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network: